services:
  # Development Bot Service with hot reload
  bot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/app/data/reminders.sqlite
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./data:/app/data
    networks:
      - remindme-network-dev

  # SQLite Web Interface for development
  sqlite-web:
    image: coleifer/sqlite-web:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=/data/reminders.sqlite
    networks:
      - remindme-network-dev

networks:
  remindme-network-dev:
    driver: bridge
