services:
  # Discord Bot Service
  bot:
    build: .
    restart: unless-stopped
    init: true
    env_file:
      - .env.production
    environment:
      - DATABASE_PATH=/app/data/reminders.sqlite
      - NODE_ENV=production
    volumes:
      - bot-data:/app/data
      - ./logs:/app/logs
    networks:
      - remindme-network-prod
    stop_signal: SIGTERM
    stop_grace_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Simple SQLite Web UI with nginx authentication
  sqlite-web:
    image: coleifer/sqlite-web:latest
    restart: unless-stopped
    command: ["sqlite_web", "-r", "-H", "0.0.0.0", "/data/reminders.sqlite"] # -r for read-only mode
    volumes:
      - bot-data:/data:ro # Read-only access for safety
    networks:
      - remindme-network-prod
    profiles:
      - debug
    # No ports exposed - only accessible via nginx

  nginx-auth:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - remindme-network-prod
    depends_on:
      - sqlite-web
    profiles:
      - debug

volumes:
  bot-data:
    driver: local

networks:
  remindme-network-prod:
    driver: bridge
