services:
  # Discord Bot Service
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/app/data/reminders.sqlite
      - NODE_ENV=production
    volumes:
      - bot-data:/app/data
      - ./logs:/app/logs
    networks:
      - remindme-network-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Database viewer for debugging
  database-viewer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
      - ADMINER_DESIGN=pepa-linha-dark
    volumes:
      - bot-data:/data
    networks:
      - remindme-network-prod
    profiles:
      - debug

volumes:
  bot-data:
    driver: local

networks:
  remindme-network-prod:
    driver: bridge
