name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Check syntax (all files)
        run: |
          for file in $(find src -name "*.js"); do
            node --check "$file"
          done

      - name: Test imports (without Discord connection)
        run: |
          node -e "import('./src/utils/timeParser.js').then(() => console.log('✅ TimeParser imports OK'))"
          node -e "import('./src/database/database.js').then(() => console.log('✅ Database imports OK'))"

      - name: Validate environment template
        run: |
          if [ -f .env.example ]; then
            echo "✅ .env.example found"
            if grep -q "DISCORD_TOKEN=" .env.example && grep -q "DISCORD_APPLICATION_ID=" .env.example; then
              echo "✅ Required environment variables present in template"
            else
              echo "❌ Missing required environment variables in template"
              exit 1
            fi
          else
            echo "❌ .env.example missing"
            exit 1
          fi

  deploy-commands:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Deploy Discord commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
        run: |
          if [ -n "$DISCORD_TOKEN" ] && [ -n "$DISCORD_APPLICATION_ID" ]; then
            npm run deploy
            echo "✅ Discord commands deployed successfully"
          else
            echo "⚠️ Skipping Discord command deployment (secrets not configured)"
          fi